### ISSUE TITLE
Using rustup & cargo together

### ISSUE THREAD

**Issue by korrat** [schuelermine/xhmm#2]
I'm using the language module for Rust. I've run into the following issue when trying to both enable `rustup` and setting `cargo` configuration:

```
error: builder for '/nix/store/pq7gizp9yn5s5q9w72bskchzx1a4fm57-home-manager-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/3svcwwimgvi62hl5a288gcpl905756h8-cargo-1.72.1/bin/cargo' and `/nix/store/0cn8dalwkmdark0zhpyn05453vb2lnds-rustup-1.26.0/bin/cargo'
```

**Comment by korrat** [comment]
For anybody else encountering this, I was able to fix it by setting

```nix
programs.rust.cargo.package = config.programs.rust.rustup.package
```

**Comment by schuelermine** [comment]
Oh this is interesting. I assumed people wouldn’t want both at the same time. I think the problem is that `rustup` ships its own `cargo` binary which is actually a wrapper that allows the use of `+nightly` and such. So installing another `cargo` is kind of a bad idea, so I think what needs to happen is that the installation of the `cargo` binary is decoupled from the enabling of cargo settings management. I will write a patch momentarily.

**Comment by schuelermine** [comment]
Luckily recently someone introduced the `nullable` parameter for `mkPackageOption`, I can use that :)
But I’ll have to use a compat thing for the time being

**Comment by schuelermine** [comment]
wait I can just use the mechanism I already use for this

**Comment by schuelermine** [comment]
god I need to look this whole repo over soon

**Comment by schuelermine** [comment]
please hold out until tomorrow

**Comment by schuelermine** [comment]
@korrat consider it fixed

**Comment by korrat** [comment]
Yup, works great. Thank you very much for the really quick response!
